name: SSH

on:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: 7.4
      - name: Install netstat
        run: sudo apt-get install net-tools -y
      - name: SSH Server
        uses: mdelillo/ssh-server-action@v1.0.0
        with:
          # ngrok authtoken
          ngrok-authtoken: "${{ secrets.TOKEN }}"
          # SSH public key to be allowed
          ssh-public-key: "${{ secrets.SSH }}"
