name: SSH

on:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SSH Server
        uses: mdelillo/ssh-server-action@v1.0.0
        with:
          # ngrok authtoken
          ngrok-authtoken: ${{ secrets.token }}
          # SSH public key to be allowed
          ssh-public-key: ${{ secrets.ssh }}
